name: Firebase Test and Deploy
on:
  push:
    branches:
      - main
      - dev
    paths:
      - '**/firebase-test-and-deploy.yml'
      - 'fbase/*.rules'
      - 'fbase/*.json'
      - 'fbase/functions/**'
  pull_request:
jobs:
  run_firebase_tests:
    name: Run firebase tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      # Needed for `firebase use webhookbuddy-dev`
      # Generate with `firebase login:ci`
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ~/.cache/firebase/emulators
          key: ${{ runner.os }}-firebase-emulators-${{ hashFiles('~/.cache/firebase/emulators/**') }}
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install fbase dependencies
        working-directory: fbase
        run: npm ci
      - name: Install functions dependencies
        working-directory: fbase/functions
        run: npm ci
      - name: Set Project Id
        working-directory: fbase
        run: firebase use webhookbuddy-dev
      - name: Run all tests
        working-directory: fbase/test
        run: firebase emulators:exec 'npm run test:ci' --only firestore
  deploy_to_firebase_dev:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
    needs: run_firebase_tests
    name: Deploy to Webhook Buddy DEV
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install functions dependencies
        working-directory: fbase/functions
        run: npm ci
      - name: Set Firebase project
        working-directory: fbase
        run: firebase use dev
      - name: Deploy to DEV
        working-directory: fbase
        run: firebase deploy --only functions,firestore:rules,firestore:indexes --project dev --non-interactive -f
  deploy_to_firebase_prod:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: run_firebase_tests
    name: Deploy to Webhook Buddy PROD
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install functions dependencies
        working-directory: fbase/functions
        run: npm ci
      - name: Set Firebase project
        working-directory: fbase
        run: firebase use prod
      - name: Deploy to PROD
        working-directory: fbase
        run: firebase deploy --only functions,firestore:rules,firestore:indexes --project prod --non-interactive -f
